### ISSUE TITLE
Consistent crash when clicking "[*]" above chat.

### ISSUE THREAD

**Issue by stephen-smith** [blay09/TwitchIntegration#21]
Modern Skyblock 3: Departed, plus TwichIntegration and ChatTweaks.

https://paste.ee/p/wREBR

I may have something misconfigured.  It's definitely authenticated with twitch, but the rest of the config is a mystery to me, and I couldn't find a guide anywhere.

**Comment by BlayTheNinth** [comment]
I assume some mod is posting an invalid message to the chat. Can you check which messages are in chat when the crash happens (and which mod they're from)? That might narrow it down so that I can reproduce it myself and find a workaround.

**Comment by stephen-smith** [comment]
https://photos.app.goo.gl/ZsWiuf8J2hPFoCz43 -- screenshot from immediately before I clicked "[*]".

**Comment by BlayTheNinth** [comment]
Buildcraft's [startup message](https://github.com/BuildCraft/BuildCraft/blob/c6b869f6a345784a1b2c5afb79e0dd733798b150/common/buildcraft/lib/BCLibEventDist.java#L140-L171) was the cause.

The latest version of Chat Tweaks contains a workaround for the issue.
