### ISSUE TITLE
Minecraft 1.16

### ISSUE THREAD

**Issue by BlayTheNinth** [blay09/TwitchIntegration#24]
Waiting on Chat Tweaks.

**Comment by KenaiTheWolf** [comment]
Is this still being worked on?

**Comment by BlayTheNinth** [comment]
I was hoping the config GUI would get reintroduced somewhere within 1.15 and holding off updating until then, since a whole bunch of Chat Tweaks (the base mod to this) depended on it, but since that didn't happen the current plan is to move most dynamic configurations (e.g. authentication, channels, views) out of the Forge framework and then just create a link between the screens once they do re-implement it.

I've started work on a 1.16 port now and will also look into slimified version that activates when Chat Tweaks isn't available (simple chat mapping without emotes).
