### ISSUE TITLE
BTTV unicode emojis are not working

### ISSUE THREAD

**Issue by yahoo1999** [blay09/TwitchIntegration#26]
I know that emojis are technically text and they are not in minecraft font. Would adding it as pictures be possible? BTTV emojis like `:+1:` don't appear in chat at all.

**Comment by yahoo1999** [comment]
Also it looks like global twitch emotes are not working as well, but it's completly different issue. Twitch subscriber emotes do work though.

**Comment by BlayTheNinth** [comment]
Unicode supports more than 3000 emoji, so adding them all isn't really feasible.
