### ISSUE TITLE
wont let me configure my twitch mod

### ISSUE THREAD

**Issue by OGDojo** [blay09/TwitchIntegration#33]
hey there been trying for an hour to set up this mod on 1.16.3 (which it says that i can do) using the twitch app, i made my modpack, downloaded the mod, enter the game, pull up my mods list... and nothing. wont let me configure or do anything, how hard is it to make a small "Read Me" File with instructions on how to integrate the mod into our game? i have been scouring the internet for any information oh now to set this mod up and have come up with NOTHING. please help, all i want to do is stream minecraft and have chat catch my attention because its hard catching chat out of the corner of my eye on a different screen.

**Comment by OGDojo** [comment]
sorry if my message seems a little terse but im frustrated cuz i have been trying to get this to work for a while now with not help or information on what i could be doing wrong

**Comment by BlayTheNinth** [comment]
how hard is it to read the mod page

> For 1.16.2, there is now a lite version available that comes without the advanced Chat Tweaks functionality (badges and emotes, high configurability) but can be used as a stopgap until Chat Tweaks is ready. Use the /twitch command ingame to get started.
