### ISSUE TITLE
/Twitch command not working

### ISSUE THREAD

**Issue by Bloomyex** [blay09/TwitchIntegration#34]
Basically, I installed the mod. But when I go into a singleplayer world and type /Twitch in the chat it basically tells me the command doesn't exist. I'm not exactly sure if I did something wrong, but I put the darn thing inside the Mods folder, so if I'm missing a step I don't know what it is?

**Comment by BlayTheNinth** [comment]
What version are you on?

**Comment by BlayTheNinth** [comment]
Should be fixed in the next version, but best to do the setup in a singleplayer world, since you might not get proper tab completions otherwise at the moment.

**Comment by Bloomyex** [comment]
Alright. Thanks!
Also, sorry for not responding a few months ago. My email needed to be fixed and I had to do other things before I could get to do it, so I couldn’t receive any new mails until that..

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
