### ISSUE TITLE
/twitch chat command not working

### ISSUE THREAD

**Issue by whitebear60** [blay09/TwitchIntegration#35]
Steps To Reproduce the Bug:

1. Install the mod
2. Go to any **vanilla** server
3. Try to execute /twitch command

Minecraft Version: 1.16.4
Forge Version: 35.1.7
TCI Version: 5.1.0

**Comment by BlayTheNinth** [comment]
Should be fixed in the next version, but best to do the setup in a singleplayer world, since you might not get proper tab completions otherwise at the moment.
