### ISSUE TITLE
Memory leak in 1.12.2? Maybe some mod incompatibility? Broken API?

### ISSUE THREAD

**Issue by IITFA** [blay09/TwitchIntegration#38]
So, I installed the twitchintegration mod and chattweaks mod and my memory usage went from around 3GB up to over 5GB and freezes there due to the limit being set to 5GB to leave some RAM left for the system. I also noticed in the log the following error:

https://pastebin.com/raw/wi9BUKLy

Upon going to the URL listed, it says "error | "This api version is gone."

I don't notice anything else in the log to suggest an issue. To verify one or both of these mods were causing the memory issue, I removed them and the RAM usage went back to normal levels. If need be, I can supply the entire MultiMC instance for testing if you want it.

**Comment by Xisdar** [comment]
I observe the same problem (

**Comment by BlayTheNinth** [comment]
Pretty much every API this mod ever touched had breaking changes since the mod originally came out. Maybe I'll port the mods to modern versions some day but the old versions are neither functional nor supported anymore.
