### ISSUE TITLE
not working when connected to a server

### ISSUE THREAD

**Issue by j-loriault** [blay09/TwitchIntegration#39]
the entire set of commands does not exist while connected to a SMP server. nor does any chat messages. even tried running it in single player first but nothing. I really enjoy this mod but for some reason it is as if it is disabling itself when connected to a server. is there any hidden config options to just make it auto connect if it already has the token and channel to join ?

**Comment by j-loriault** [comment]
![Screenshot_163](https://user-images.githubusercontent.com/72262951/142339406-cd573dda-97c6-4b3d-97de-0869542552a6.png)

**Comment by BlayTheNinth** [comment]
Closing since all currently released versions are no longer supported
