### ISSUE TITLE
Error thrown when trying to join channel that is hosting someone else

### ISSUE THREAD

**Issue by xSparky911x** [blay09/TwitchIntegration#8]
As per the title, My channel is set to auto host. If I am currently hosting someone else and launch my game Twitch integration throws an error "unhandled exception". If I exit host mode all is well.

Forge 2185
Twitch Integration 2.1.6
Chat Tweakes 4.1.6

http://pastebin.com/1XSKZCRn

**Comment by BlayTheNinth** [comment]
This was fixed as part of the rewrite for Minecraft 1.11.2.
